### ISSUE TITLE
Open CV version

### ISSUE THREAD

**Issue by SiddharthBhawsar** [1751200/Panorama-Stitching#1]
Hello,

I'm working on a similar project and found your repository as a super helpful resource. While running this project on my system, I was getting the following error:  

ESTIMATOR_CHOICES['homography'] = cv.detail_HomographyBasedEstimator
AttributeError: module 'cv2.cv2' has no attribute 'detail_HomographyBasedEstimator'

Could you please tell me if there is any specific version of OpenCV you used for it? I'm currently using 3.4.4.19.
I would appreciate your help. Thanks

**Comment by troysung** [comment]
I don't actually remember the details of the project, but for your information I'm currently working on 4.5.1, which contains the attribute `detail_HomographyBasedEstimator `. I hope this helps you.

**Comment by SiddharthBhawsar** [comment]
Thanks so much for replying. I've tried implementing a similar graph-cut approach in my system. The app in itself is complete. I want to focus on a small part of it. Can we please have a 15-minute zoom meeting if you're available anytime this week? I'm super interested in learning more about this project. 
You can use this link to let me know your availability. https://calendly.com/d/dhp-svx-n5w/30-minute-meeting
Thanks.
Siddharth
